name: Github Actions on SNU_Computing_Commons
run-name: ${{ github.actor }} is testing out Github Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: 'My ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3
      
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: v20.9.0

      - name: 'Download deps'
        run: npm install
